### ISSUE TITLE
Seems doesn't work?

### ISSUE THREAD

**Issue by li0817** [scottTomaszewski/obsidian-inline-admonitions#11]
Settings:
![image](https://github.com/scottTomaszewski/obsidian-inline-admonitions/assets/27659768/5457fd7d-8fb6-4a37-b494-8eddb7d7411d)

I've tried many times but nothing's change, just plain text as usual.
![image](https://github.com/scottTomaszewski/obsidian-inline-admonitions/assets/27659768/14bbfb48-7a05-4ece-a1ac-c32c955d7bc6)

**Comment by scottTomaszewski** [comment]
The admonition needs to be wrapped in backticks (`). In your example, try

```
`ABC 100`
```
With a backtick before the "ABC" and a backtick after the "100"

Let me know if that helps

**Comment by li0817** [comment]
> The admonition needs to be wrapped in backticks (`). In your example, try
> 
> ```
> `ABC 100`
> ```
> 
> With a backtick before the "ABC" and a backtick after the "100"
> 
> Let me know if that helps

I've tried doing this, but it's still the same as the default inline code. 
![image](https://github.com/scottTomaszewski/obsidian-inline-admonitions/assets/27659768/9adcaa4e-7710-4b26-b4df-50889d356656)
I've also tried using the default theme of obsidian and turning off all other plug-ins. Still, it remains the same. 
I don't know where it went wrong, is there any other way to troubleshoot the problem?

**Comment by scottTomaszewski** [comment]
hmmm thats odd.  Can you try looking in the console (Ctrl + Shift + i) to see if there are any errors?  

Oh, is this in live-preview mode?  I am currently working on getting live-preview mode working, but in the public release its not available.

**Comment by li0817** [comment]
> hmmm thats odd. Can you try looking in the console (Ctrl + Shift + i) to see if there are any errors?
> 
> Oh, is this in live-preview mode? I am currently working on getting live-preview mode working, but in the public release its not available.

Problem solved! Thanks, I really didn't think of that. 
Once I switch into the reading view, it works properly. It's all good now.
![image](https://github.com/scottTomaszewski/obsidian-inline-admonitions/assets/27659768/34624d51-6f1e-4404-8911-4882d8111262)
I recommend putting this issue to the document so that others won't run into the same problem.

**Comment by profucius** [comment]
> I am currently working on getting live-preview mode working, but in the public release its not available.

I hope you can find a way to get this working. I'd love to have this plugin working in the Editing view (non-reading view) while I am editing a document.

**Comment by scottTomaszewski** [comment]
> > I am currently working on getting live-preview mode working, but in the public release its not available.
> 
> I hope you can find a way to get this working. I'd love to have this plugin working in the Editing view (non-reading view) while I am editing a document.
> 
> Edit: It seems to work now after restarting Obsidian for some reason.

So sorry for the failure to communicate.  Inline Admonitions should function in Live Preview **_after a reload_**.  There is a funky issue right now that I have mentioned in the readme: https://github.com/scottTomaszewski/obsidian-inline-admonitions?tab=readme-ov-file#known-issues
Its super subtle; my fault. 

Anyway, enable the plugin then reload the app and everything should function.  Ill try to get to the bottom of the issue

**Comment by profucius** [comment]
That explains it! Not a huge deal to me at the moment, but glad to hear you're looking into a solution. Your plugin has a lot of use for me!

**Comment by scottTomaszewski** [comment]
Update: I think this should be fixed in 1.4.6
Seems to work for me at least.  Let me know if its still causing issues for you @profucius

**Comment by profucius** [comment]
It works! This is awesome 🎉
